name: Master branch updater.
  
on:
  release:
    types: released

jobs:
  User-agent:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
        with:
          type: "dev-to-master"
